# Change these first
owner: minemobs # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Maven Repo
    url: https://maven.galaxyfight.fr
  - name: TheSimpleTeam
    url: https://thesimpleteam.net

assignees:
  - minemobs

status-website:
  #cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  theme: dark
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO